### ISSUE TITLE
Test script hangs on take

### ISSUE THREAD

**Issue by sharonovd** [tarantool/sharded-queue#1]
Original report from user:

Hello!
I'm running a simple test:
```lua
netbox = require('net.box')
queue_conn = netbox.connect(...)
while ( true ) do
   queue_conn:call('queue.create_tube', {'t1'})
   for i = 1, 100 do
      queue_conn:call('queue.tube.t1:put', { 'T' .. i })
      print ( 'PUT ' .. i )
   end
   for i = 1, 100 do
      queue_conn:call('queue.tube.t1:take')
      print ( 'TAKE ' .. i )
   end
   queue_conn:call('queue.tube.t1:drop')
end
```
After some time it hangs on a some TAKE. And every time after restart it's always hangs on at TAKE99 until the tube is deleted

**Comment by vanyarock01** [comment]
I could not reproduce the problem on the last version. Please, update and try again.

**Comment by vanyarock01** [comment]
The error occurred on the test stand of the new sharded-queue version.

**Comment by Alex-Kuz** [comment]
There is a viable hypothesis:
In the case of exponential rollback, the wait time for the next attempt to `take` may exceed the TTL of the added task, which leads to the fact that the task may appear in the queue and leave due to TTL between `take` attempt.

**Comment by akudiyar** [comment]
Not reproducible on new versions, closed
