### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by subjrs** [tarantool/sharded-queue#14]
Hi! I'm trying to run build by:
`tarantoolctl rocks make`
and getting error:
```
Warning: variable CFLAGS was not passed in build_variables
make: *** No rule to make target `all'.  Stop.
```

**Comment by vanyarock01** [comment]
Hi, please report the OS and tarantool version.

**Comment by subjrs** [comment]
> Hi, please report the OS and tarantool version.

Hello!

CentOS Linux release 7.4.1708
tarantool-enterprise-1.10.5-9

**Comment by subjrs** [comment]
If I set 
```
> type = 'builtin',
> modules = {},
```
instead
```
< type = 'make',
< build_target = 'all',
```
in sharded-queue-scm-1.rockspec, the build is successful.
We have make-3.82-23.el7.x86_64
