### ISSUE TITLE
Excessive CPU usage on `take`

### ISSUE THREAD

**Issue by sharonovd** [tarantool/sharded-queue#16]
Currently each `take` operation (with all timeouts set to default) leads to 100 calls from router to storages (if no suitable task is found).
On a real traffic, it shows as excessive 30% CPU usage on a router, and few thousand "parasite" CALL/SELECT RPS on storages.

This could be improved using two approaches:
a) use exponential back-offs for long-polling calls to storages.
 + +easy to implement
 + +no risk to lose `cached` tasks on routers
 - -some parasite CPU usage will still remain (however it will be at least a magnitude smaller)

b) long-poll tasks to routers from all storages in parallel, cache them and serve to clients
 + +optimal number of network calls
 - -harder to implement correctly
 - -some tasks will not be really `taken` if a router is restarted or moved out from load

I propose to implement approach a)

**Comment by Alex-Kuz** [comment]
Closed in https://github.com/tarantool/sharded-queue/pull/17

**Comment by akudiyar** [comment]
/bug /resolved

Awaiting for verification by the initial reporters.
