### ISSUE TITLE
API role only available in Master

### ISSUE THREAD

**Issue by pnvasanth** [tarantool/sharded-queue#37]
Hi, 

Based on the below config, If we try to connect using port 3303 or 3305,  we are getting variable 'queue' is not declared error.
 
![image](https://user-images.githubusercontent.com/439478/94288417-472f4180-ff4f-11ea-9772-3137bdef5118.png)

----------------------------------------
connected to localhost:3301
localhost:3301> queue
---
- tube:
    ssssss:
      log_request: false
      tube_name: ssssss
      wait_factor: 2
  statistics: 'function: 0x0115f4cbe8'
  create_tube: 'function: 0x0115f4cc28'
...
---------------------------------------------

connected to localhost:3303
localhost:3303> queue
---
- error: '[string "return queue"]:1: variable ''queue'' is not declared'
...
---------------------------------------------

**Comment by akudiyar** [comment]
Queue API is available only on master nodes since any operation requires writing data into the internal tube space (even the `take` operation changes the task status).

**Comment by pnvasanth** [comment]
@akudiyar Thank you, For any operation data changes are only happening in storage nodes right?  The router nodes which is having a Queue API are just routing the requests to storage nodes and holding the tube status in memory.  
Could you please clarify, it will help me to understand.

**Comment by akudiyar** [comment]
@pnvsanth Queue module init is possible only on rw (master) nodes because of collecting statistics. It is saved into a space on router, and  therefore cannot be saved on a ro node.

**Comment by slawo** [comment]
On our end we start routers with all_rw mode and queue is still not available on non master nodes

**Comment by akudiyar** [comment]
@slawo in this case in `api` role the `opts.is_master` check may be transforned into `box.status.ro == false` or `box.cfg.read_only == false`.  Would you mind creating a PR?
